### ISSUE TITLE
Item3翻译改进

### ISSUE THREAD

**Issue by zypy333** [clxering/Effective-Java-3rd-edition-Chinese-English-bilingual#119]
**The location of the content：（内容所在位置）：**

chapter 2 Item 3

**Description and expected results（描述及预期结果）：**
To make a singleton class that uses either of these approaches serializable (Chapter 12)

要使单例类使用这两种方法中的任何一种**序列化**（Chapter 12），仅仅在其声明中添加实现 serializable 是不够的

**Comment by clxering** [comment]
@zypy333 感谢建议，已做修改：[dev commit](https://github.com/clxering/Effective-Java-3rd-edition-Chinese-English-bilingual/commit/486247d6c4aaf942d11e431ba71fefbe347009d5)
