### ISSUE TITLE
翻译质量改进

### ISSUE THREAD

**Issue by zjgyjd** [clxering/Effective-Java-3rd-edition-Chinese-English-bilingual#121]
**The location of the content：（内容所在位置）：**

Item 18 ,where "the wrapper class can be used to instrument any Set implementation and will work in conjunction with any preexisting constructor:"
翻译为:包装器类可用于仪器任何集合实现，并将与任何现有构造函数一起工作

**Description and expected results（描述及预期结果）：
上述翻译可以改进为: 包装类可以用来给任何Set实现类进行计算,并将与任何现有构造函数一起工作

**Comment by YujingGao96** [comment]
instrument 翻译为“装配”更为合适。

包装类可以用来装配任何Set的实现，同时可以与任何现有构造函数一起工作

**Comment by clxering** [comment]
感谢建议 @zjgyjd @YujingGao96 

1、考虑将 instrumentation 译为「插装」，类比硬盘（Set）插装到主板（ForwardingSet），无论硬盘如何更新换代，但是用于存储的功能不会变。外设（客户端）通过主板的 USB2.0 口（InstrumentedSet2.0）或 USB3.0 口（InstrumentedSet3.0），与硬盘交互，使用其存储功能。

2、提及的句子“...the wrapper class can be used to instrument any Set implementation and will work in conjunction with any preexisting constructor......”，译文考虑改为“包装器类可用于插装任何 Set 实现，并将与任何现有构造函数一起工作”

上述修改已经提交，如有其他看法，欢迎继续提出。
