### ISSUE TITLE
Typo: Chapter-2 Item-2

### ISSUE THREAD

**Issue by beeeeeeeeck** [clxering/Effective-Java-3rd-edition-Chinese-English-bilingual#122]
**The location of the content：（内容所在位置）：**

Item 2

与构造函数相比，构造函数的一个小优点是构造函数可以有多个变量参数，因为每个参数都是在自己的方法中指定的。或者，构建器可以将传递给一个方法的多个调用的参数聚合到单个字段中，如前面的 addTopping 方法中所示。

**Description and expected results（描述及预期结果）：**
与构造函数相比，**构建器**的一个小优点是**构建器**可以有多个变量参数，因为每个参数都是在自己的方法中指定的。或者，构建器可以将传递给一个方法的多个调用的参数聚合到单个字段中，如前面的 addTopping 方法中所示。

**Comment by YujingGao96** [comment]
> **The location of the content：（内容所在位置）：**
> 
> Item 2
> 
> 与构造函数相比，构造函数的一个小优点是构造函数可以有多个变量参数，因为每个参数都是在自己的方法中指定的。或者，构建器可以将传递给一个方法的多个调用的参数聚合到单个字段中，如前面的 addTopping 方法中所示。
> 
> **Description and expected results（描述及预期结果）：**
> 与构造函数相比，**构建器**的一个小优点是**构建器**可以有多个变量参数，因为每个参数都是在自己的方法中指定的。或者，构建器可以将传递给一个方法的多个调用的参数聚合到单个字段中，如前面的 addTopping 方法中所示。

构造函数和构建器是同义词 都可以用来表示constructor。

**Comment by clxering** [comment]
感谢建议 @beeeeeeeeck @YujingGao96 

不当之处已做修改，如有其他看法，欢迎继续提出。
