### ISSUE TITLE
翻译计划问题

### ISSUE THREAD

**Issue by CYXK** [clxering/Effective-Java-3rd-edition-Chinese-English-bilingual#61]
**Technical discussion or constructive comments（技术讨论或建议的详细描述）:**
我看了一下，翻译工作还未完成，是否可以增加翻译计划的排期，就是当前正在翻译的和待翻译的内容，然后我们其他人如果有时间，也可以根据计划表认领待翻译内容，这样可以加速翻译进程。

**Comment by clxering** [comment]
感谢您对这个翻译项目的关注！
这个项目建立至今已经有约半年时间，虽然内容、结构都在逐步完善，但期间由于工作、生活的原因，时常难以兼顾，导致翻译进度缓慢。对于您的建议，我是这么想的：
目前纠错、校对、初始化译文等等流程，可以通过 pr 的方式开展，都可以按照个人喜好进行选择，就当下参与人数来看，应该还不至于产生冲突。后续是否增加翻译计划或排期，视看参与人数再决定吧。如果有了一定规模，可能将项目转为组织，这样也能够更好的进行管理和维护，或许还能够开展其他书籍或资料的翻译。
相信对于大多数人来说，翻译只是业余时间的爱好之一，当然，这也是一种学习方式，也希望今后能以此够结识更多的同道中人，互相交流提高，共勉。

**Comment by CYXK** [comment]
好的，了解了
