### ISSUE TITLE
一口气翻译完了，未勘误

### ISSUE THREAD

**Issue by 1976222027** [clxering/Effective-Java-3rd-edition-Chinese-English-bilingual#66]
**Technical discussion or constructive comments（技术讨论或建议的详细描述）:**
https://github.com/1976222027/effective-java-3/raw/master/Effective%20Java%E7%AC%AC%E4%B8%89%E7%89%88.docx

**Comment by clxering** [comment]
好的，感谢分享。
等您勘误校对完成，我会前往拜读。
