### ISSUE TITLE
item 17: A special case 建议

### ISSUE THREAD

**Issue by le0zh0u** [clxering/Effective-Java-3rd-edition-Chinese-English-bilingual#83]
**The location of the content：（内容所在位置）：**

Item 17. Minimize mutability
> Immutable objects make great building blocks for other objects, whether mutable or immutable. It’s much easier to maintain the invariants of a complex object if you know that its component objects will not change underneath it. A special case of this principle is that immutable objects make great map keys and set elements: you don’t have to worry about their values changing once they’re in the map or set, which would destroy the map or set’s invariants.

**Description and expected results（描述及预期结果）：**

这里的`A Special case`是不是应该是`一个具体的例子`

**Comment by clxering** [comment]
Chapter 4 的译文确实有比较多问题，欢迎 pr，给出修正意见。

**Comment by clxering** [comment]
同意你的观点，已经修改到 `review-chapter-4` 分支。 @le0zh0u 

`A Special case` 更多时候译为「特例」或「特殊情况」，但是这句原文意在说明 Map 的键和 Set 的元素是不应该被改变的，否则会破坏 Map 或 Set 的不变性，也无法通过编译。Map 的键值必须唯一众所周知，对于 Set，如果结合泛型理解应该会更好，例如 `Set<Integer>`，此时元素只能是 Integer 类型，放入其他类型则编译器报错。

所以，译为「一个具体的例子」我认为语义上没有问题，逻辑上也说得通。
