### ISSUE TITLE
Chapter2 Item7 翻译改进

### ISSUE THREAD

**Issue by yi-yun** [clxering/Effective-Java-3rd-edition-Chinese-English-bilingual#98]
**The location of the content：（内容所在位置）：**

Item 7: Eliminate obsolete object references（排除过时的对象引用）

**Description and expected results（描述及预期结果）：**
> any object references contained in the element should be nulled out.
> 元素中包含的任何对象引用都应该被取消

个人认为翻译成”任何对象引用都应该被置为 null“ 会更有助于阅读。

**Comment by clxering** [comment]
已修改，感谢建议。
